Repository NOWSOPT-CDSP-WEB-7/YES24-WEB-CLIENT, pull requests merged in 2024-05, with the labels that each got.

#3 [Init] 스타일린트 & 스타일 컴포넌트 세팅
  .stylelintrc
  package.json
  yarn.lock
Labels: 다은, ⛓️ Init

#5 [Init] eslint & prettier 적용 및 충돌 방지
  .eslintignore
  .eslintrc.cjs
  .prettierignore
  .prettierrc.json
  package.json
  yarn.lock
Labels: ⛓️ Init, 준혁

#8 [Init] GlobalStyle & theme 파일 생성 및 내용 추가
  package.json
  src/main.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  yarn.lock
Labels: ⛓️ Init, 화랑

#10 [Init] Svg 리액트 컴포넌트로 불러오기
  package.json
  svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 다은, ⛓️ Init

#17 [Feat] 검색페이지 헤더 구현
  src/Router.tsx
  src/assets/icons/ic_backBtn.svg
  src/assets/icons/index.ts
  src/components/SearchHeader/SearchHeader.styled.ts
  src/components/SearchHeader/SearchHeader.tsx
  src/pages/Search/Search.styled.ts
  src/pages/Search/Search.tsx
  src/styles/theme.ts
Labels: ✨ Feature, 화랑

#16 [Fix] 헤더 수정사항 반영
  src/components/commons/Header.styled.ts
  src/components/commons/Header.tsx
Labels: 다은, ⚒️ Fix

#21 [Feat] 공연 디테일 정보 UI 퍼블리싱
  .eslintrc.cjs
  package.json
  src/Router.tsx
  src/assets/icons/ic_btnShare.svg
  src/assets/icons/ic_chevron_up.svg
  src/assets/icons/ic_globalBtn.svg
  src/assets/icons/ic_hamburger.svg
  src/assets/icons/ic_heart_empty.svg
  src/assets/icons/ic_heart_fill.svg
  src/assets/icons/ic_line.svg
  src/assets/icons/ic_logo_svg.svg
  src/assets/icons/ic_my.svg
  src/assets/icons/ic_search.svg
  src/assets/icons/ic_yes24Btn.svg
  src/assets/icons/index.ts
  src/assets/images/show.png
  src/components/commons/Footer/Footer.styled.ts
  src/components/commons/Footer/Footer.tsx
  src/components/commons/Header/Header.styled.ts
  src/components/commons/Header/Header.tsx
  src/constants/footer.ts
  src/constants/showDetailCategory.ts
  src/constants/showDetailData.ts
  src/main.tsx
  src/pages/Detail/Detail.styled.ts
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/ShowInfo.styled.ts
  src/pages/Detail/components/ShowInfo.tsx
  src/pages/Detail/types/showDetailTypes.ts
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 다은, ✨ Feature

#19 [Feat] 메인 캐러셀 구현 + 메인페이지(생성)
  .eslintrc.cjs
  .stylelintrc
  package.json
  src/Router.tsx
  src/assets/icons/ic_only_box.svg
  src/assets/icons/index.ts
  src/assets/mainCarouselImgs/paganini.png
  src/assets/mainCarouselImgs/등등곡.png
  src/assets/mainCarouselImgs/디어에반핸슨.png
  src/assets/mainCarouselImgs/어쩌면해피엔딩.png
  src/assets/mainCarouselImgs/이블데드.png
  src/assets/mainCarouselImgs/이찬원콘서트.png
  src/components/commons/Footer/Footer.styled.ts
  src/components/commons/Footer/Footer.tsx
  src/components/commons/Header/Header.styled.ts
  src/components/commons/Header/Header.tsx
  src/constants/mainCarousel.ts
  src/pages/Main/Main.styled.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCarousel/MainCarousel.styled.ts
  src/pages/Main/components/MainCarousel/MainCarousel.tsx
  src/pages/Main/components/MainCarousel/swiperStyles.css
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 준혁

#24 [Feat] 할인 쿠폰 컴포넌트 UI 구현
  src/assets/icons/ic_download.svg
  src/assets/icons/index.ts
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/SaleCoupon.styled.ts
  src/pages/Detail/components/SaleCoupon.tsx
Labels: 다은, ✨ Feature

#25 [Feat] SearchBar & 실시간 검색 구현
  .gitignore
  package.json
  public/data/search-result.json
  src/assets/icons/ic_cancel.svg
  src/assets/icons/index.ts
  src/hooks/useChangeInput.ts
  src/hooks/useGetSearchResult.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/SearchBar/SearchBar.styled.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/Search/components/SearchHeader/SearchHeader.styled.ts
  src/pages/Search/components/SearchHeader/SearchHeader.tsx
  src/pages/Search/components/SearchList/SearchList.styled.ts
  src/pages/Search/components/SearchList/SearchList.tsx
  yarn.lock
Labels: ✨ Feature, 화랑

#26 [Feat] 카테고리 뷰 UI & 카테고리에 따른 컴포넌트 렌더링
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/Category.styled.ts
  src/pages/Detail/components/Category.tsx
  src/pages/Detail/components/ExpectComment.tsx
  src/pages/Detail/components/Info.tsx
  src/pages/Detail/components/ProductInfo.tsx
  src/pages/Detail/components/ShowPoster.tsx
Labels: 다은, ✨ Feature

#30 [Feat] 랭킹 컴포넌트 구현
  src/assets/icons/ic_chevron-right.svg
  src/assets/icons/ic_devider_10px.svg
  src/assets/icons/index.ts
  src/assets/rankingCarouselImgs/rank1.png
  src/assets/rankingCarouselImgs/rank2.png
  src/assets/rankingCarouselImgs/rank3.png
  src/assets/rankingCarouselImgs/김창옥.png
  src/assets/rankingCarouselImgs/나훈아.png
  src/assets/rankingCarouselImgs/로이킴.png
  src/constants/mainCarousel.ts
  src/constants/rankingCarousel.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/MainCarousel/MainCarousel.styled.ts
  src/pages/Main/components/MainCarousel/MainCarousel.tsx
  src/pages/Main/components/MainCarousel/swiperStyles.css
  src/pages/Main/components/RankingComponent/RankingComponent.styled.ts
  src/pages/Main/components/RankingComponent/RankingComponent.tsx
  src/pages/Main/components/RankingComponent/rankingSwiperStyles.css
  src/pages/Main/components/RankingComponent/swiperStyles.css
  src/styles/theme.ts
  src/utils/formatData.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 준혁

#32 [Feat] 검색어 입력시 실시간 서칭 & SearchList 구현
  src/assets/images/show.png
  src/components/commons/Header.styled.ts
  src/components/commons/Header.tsx
  src/pages/Search/components/SearchList/SearchList.styled.ts
  src/pages/Search/components/SearchList/SearchList.tsx
Labels: ✨ Feature, 화랑

#37 [Feat] 티켓오픈/공지 컴포넌트, IcMainBanner 구현
  src/assets/TicketOpenImgs/공지1.png
  src/assets/TicketOpenImgs/공지2.png
  src/assets/TicketOpenImgs/공지3.png
  src/assets/icons/ic_main_banner.svg
  src/assets/icons/index.ts
  src/constants/ticketopen.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/TicketOpen/TicketOpen.styled.ts
  src/pages/Main/components/TicketOpen/TicketOpen.tsx
Labels: ✨ Feature, 준혁

#40 [Feat] 최근 검색어 RecentWord 컴포넌트 구현
  src/pages/Search/Search.tsx
  src/pages/Search/components/RecentWord/RecentWord.styled.ts
  src/pages/Search/components/RecentWord/RecentWord.tsx
  src/pages/Search/components/RecentWords/RecentWords.styled.ts
  src/pages/Search/components/RecentWords/RecentWords.tsx
Labels: ✨ Feature, 화랑

#39 [Feat] 하단 메인 배너 UI 구현
  src/assets/cardBannerImgs/card_1.png
  src/assets/cardBannerImgs/card_2.png
  src/assets/cardBannerImgs/card_3.png
  src/assets/cardBannerImgs/card_4.png
  src/assets/cardBannerImgs/card_5.png
  src/assets/cardBannerImgs/card_6.png
  src/assets/cardBannerImgs/card_7.png
  src/constants/mainCardBanners.ts
  src/pages/Main/Main.tsx
  src/pages/Main/components/CardBanner/CardBanner.styled.ts
  src/pages/Main/components/CardBanner/CardBanner.tsx
Labels: ✨ Feature, 준혁

#43 [Feat] 최근 검색 공연 컴포넌트 구현
  src/components/commons/DeleteAllBtn/DeleteAllBtn.styled.ts
  src/components/commons/DeleteAllBtn/DeleteAllBtn.tsx
  src/components/commons/SearchedShow/SearchedShow.styled.ts
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/pages/Search/components/RecentShows/RecentShows.styled.ts
  src/pages/Search/components/RecentShows/RecentShows.tsx
Labels: ✨ Feature, 화랑

#45 [Feat] search/list 페이지 필터링 구현
  src/Router.tsx
  src/assets/icons/ic_dropdownBtn.svg
  src/assets/icons/index.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/CategoryTab/CategoryTab.tsx
  src/pages/SearchListPage/SearchListPage.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
  src/pages/SearchListPage/components/Filters/Filters.styled.ts
  src/pages/SearchListPage/components/Filters/Filters.tsx
Labels: ✨ Feature, 화랑

#50 [Feat] 공연 정보 카테고리 뷰 구현
  src/assets/images/banner1.png
  src/assets/images/banner2.png
  src/assets/images/showImg1.png
  src/assets/images/showImg2.png
  src/constants/detailInfo.ts
  src/pages/Detail/Detail.styled.ts
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/Category/Category.styled.ts
  src/pages/Detail/components/Category/Category.tsx
  src/pages/Detail/components/ExpectComment/ExpectComment.tsx
  src/pages/Detail/components/Info.tsx
  src/pages/Detail/components/Info/Info.styled.ts
  src/pages/Detail/components/Info/Info.tsx
  src/pages/Detail/components/ProductInfo/ProductInfo.tsx
  src/pages/Detail/components/SaleCoupon/SaleCoupon.styled.ts
  src/pages/Detail/components/SaleCoupon/SaleCoupon.tsx
  src/pages/Detail/components/ShowInfo/ShowInfo.styled.ts
  src/pages/Detail/components/ShowInfo/ShowInfo.tsx
  src/pages/Detail/components/ShowPoster/ShowPoster.tsx
  src/styles/theme.ts
Labels: 다은, ✨ Feature

#55 [Feat] Detail 뷰 하단 예매하기 버튼
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/ReserveBtn/ReserveBtn.styled.ts
  src/pages/Detail/components/ReserveBtn/ReserveBtn.tsx
Labels: 다은, ✨ Feature

#54 [Fix] 공통 헤더 position 추가
  src/components/commons/Header.styled.ts
Labels: 다은, ⚒️ Fix

#46 [Feat] 모달 구현 (뷰 마무리)
  index.html
  src/assets/icons/ic_checkbox.svg
  src/assets/icons/index.ts
  src/assets/modalImgs/modal_banner1.png
  src/assets/modalImgs/modal_banner2.png
  src/pages/Main/Main.tsx
  src/pages/Main/components/Modal/Modal.styled.ts
  src/pages/Main/components/Modal/Modal.tsx
Labels: ✨ Feature, 준혁

#58 [Merge] feat/Detail -> develop
  .eslintrc.cjs
  src/Router.tsx
  src/assets/icons/ic_btnShare.svg
  src/assets/icons/ic_condition.svg
  src/assets/icons/ic_download.svg
  src/assets/icons/ic_heart_empty.svg
  src/assets/icons/ic_heart_fill.svg
  src/assets/icons/ic_more.svg
  src/assets/icons/ic_refund.svg
  src/assets/icons/ic_table.svg
  src/assets/icons/index.ts
  src/assets/images/banner1.png
  src/assets/images/banner2.png
  src/assets/images/poster.png
  src/assets/images/show.png
  src/assets/images/showImg1.png
  src/assets/images/showImg2.png
  src/assets/images/table.png
  src/components/commons/Footer/Footer.styled.ts
  src/components/commons/Footer/Footer.tsx
  src/components/commons/Header/Header.styled.ts
  src/components/commons/Header/Header.tsx
  src/constants/commentCategory.ts
  src/constants/detailInfo.ts
  src/constants/showDetailCategory.ts
  src/constants/showDetailData.ts
  src/pages/Detail/Detail.styled.ts
  src/pages/Detail/Detail.tsx
  src/pages/Detail/components/Category/Category.styled.ts
  src/pages/Detail/components/Category/Category.tsx
  src/pages/Detail/components/ExpectComment/ExpectComment.styled.ts
  src/pages/Detail/components/ExpectComment/ExpectComment.tsx
  src/pages/Detail/components/Info/Info.styled.ts
  src/pages/Detail/components/Info/Info.tsx
  src/pages/Detail/components/ProductInfo/ProductInfo.styled.ts
  src/pages/Detail/components/ProductInfo/ProductInfo.tsx
  src/pages/Detail/components/ReserveBtn/ReserveBtn.styled.ts
  src/pages/Detail/components/ReserveBtn/ReserveBtn.tsx
  src/pages/Detail/components/SaleCoupon/SaleCoupon.styled.ts
  src/pages/Detail/components/SaleCoupon/SaleCoupon.tsx
  src/pages/Detail/components/ShowInfo/ShowInfo.styled.ts
  src/pages/Detail/components/ShowInfo/ShowInfo.tsx
  src/pages/Detail/components/ShowPoster/ShowPoster.styled.ts
  src/pages/Detail/components/ShowPoster/ShowPoster.tsx
  src/pages/Detail/types/showDetailTypes.ts
  src/styles/theme.ts
Labels: 🧩 Merge

#60 [Merge] feat/Search -> develop
  .gitignore
  package.json
  public/data/search-result.json
  src/Router.tsx
  src/assets/icons/ic_backBtn.svg
  src/assets/icons/ic_cancel.svg
  src/assets/icons/ic_dropdownBtn.svg
  src/assets/icons/index.ts
  src/assets/images/show.png
  src/components/commons/DeleteAllBtn/DeleteAllBtn.styled.ts
  src/components/commons/DeleteAllBtn/DeleteAllBtn.tsx
  src/components/commons/Header/Header.styled.ts
  src/components/commons/SearchedShow/SearchedShow.styled.ts
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/hooks/useChangeInput.ts
  src/hooks/useGetSearchResult.ts
  src/pages/Search/Search.styled.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/CategoryTab/CategoryTab.styled.ts
  src/pages/Search/components/CategoryTab/CategoryTab.tsx
  src/pages/Search/components/RecentShows/RecentShows.styled.ts
  src/pages/Search/components/RecentShows/RecentShows.tsx
  src/pages/Search/components/RecentWord/RecentWord.styled.ts
  src/pages/Search/components/RecentWord/RecentWord.tsx
  src/pages/Search/components/RecentWords/RecentWords.styled.ts
  src/pages/Search/components/RecentWords/RecentWords.tsx
  src/pages/Search/components/SearchBar/SearchBar.styled.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/Search/components/SearchHeader/SearchHeader.styled.ts
  src/pages/Search/components/SearchHeader/SearchHeader.tsx
  src/pages/Search/components/SearchList/SearchList.styled.ts
  src/pages/Search/components/SearchList/SearchList.tsx
  src/pages/SearchListPage/SearchListPage.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
  src/pages/SearchListPage/components/Filters/Filters.styled.ts
  src/pages/SearchListPage/components/Filters/Filters.tsx
  src/styles/theme.ts
  yarn.lock
Labels: 🧩 Merge

#57 [Feat] SearchList, Search 컴포넌트 수정
  src/Router.tsx
  src/pages/Search/Search.styled.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/CategoryTab/CategoryTab.tsx
  src/pages/Search/components/SearchBar/SearchBar.styled.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/Search/components/SearchList/SearchList.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
Labels: ⚒️ Fix, 화랑

#61 [Merge] feat/Search -> develop
  src/Router.tsx
  src/pages/Search/Search.styled.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/CategoryTab/CategoryTab.tsx
  src/pages/Search/components/SearchBar/SearchBar.styled.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/Search/components/SearchList/SearchList.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
Labels: 🧩 Merge

#63 [Fix] 경로 에러 및 타입 에러 수정
  src/components/commons/SearchedShow/SearchedShow.styled.ts
  src/hooks/useChangeInput.ts
  src/pages/Search/Search.tsx
  src/pages/Search/components/RecentWord/RecentWord.tsx
  src/pages/Search/components/RecentWords/RecentWords.tsx
  src/pages/Search/components/SearchList/SearchList.tsx
  src/pages/SearchListPage/components/Filters/Filters.tsx
Labels: ⚒️ Fix, 화랑

#70 [Feat] 검색어 localStorage에 저장 및 get api요청 로직 구현
  .gitignore
  src/apis/SearchApi/getSearchResult.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
Labels: ✨ Feature, 화랑

#75 [Feat] 검색 결과를 받아오는 API GET
  src/apis/SearchApi/getSearchResult.ts
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/hooks/useChangeInput.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/SearchListPage/SearchListPage.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
  src/pages/SearchListPage/components/FilteredResultList/FilteredResultList.styled.ts
  src/pages/SearchListPage/components/FilteredResultList/FilteredResultList.tsx
  src/pages/SearchListPage/components/Filters/Filters.tsx
  src/pages/SearchListPage/components/FiltersAndResult/FiltersAndResult.tsx
  tsconfig.json
  vite.config.ts
Labels: 화랑, 🚀 API

#74 [Fix] 이미지 사이 공백 제거
  src/pages/Detail/components/ExpectComment/ExpectComment.styled.ts
  src/pages/Detail/components/Info/Info.styled.ts
  src/pages/Detail/components/Info/Info.tsx
  src/pages/Detail/components/ProductInfo/ProductInfo.styled.ts
  src/pages/Detail/components/ShowPoster/ShowPoster.styled.ts
  src/pages/Detail/components/ShowPoster/ShowPoster.tsx
Labels: 다은, ⚒️ Fix

#77 [Feat] 검색 결과들의 장르에 따라 필터 개수 변경
  .gitignore
  src/apis/SearchApi/getSearchResult.ts
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/hooks/useChangeInput.ts
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/SearchListPage/SearchListPage.styled.ts
  src/pages/SearchListPage/SearchListPage.tsx
  src/pages/SearchListPage/components/FilteredResultList/FilteredResultList.styled.ts
  src/pages/SearchListPage/components/FilteredResultList/FilteredResultList.tsx
  src/pages/SearchListPage/components/Filters/Filters.styled.ts
  src/pages/SearchListPage/components/Filters/Filters.tsx
  src/pages/SearchListPage/components/FiltersAndResult/FiltersAndResult.tsx
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 화랑

#82 [Feat] detail 페이지로 라우팅
  src/components/commons/SearchedShow/SearchedShow.styled.ts
  src/components/commons/SearchedShow/SearchedShow.tsx
Labels: ✨ Feature, 화랑

#86 [Feat] /search/list 페이지에서 재검색 안되는 에러 수정
  src/apis/SearchApi/getSearchResult.ts
  src/components/commons/DeleteAllBtn/DeleteAllBtn.tsx
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/main.tsx
  src/pages/Search/components/RecentWord/RecentWord.tsx
  src/pages/Search/components/RecentWords/RecentWords.styled.ts
  src/pages/Search/components/RecentWords/RecentWords.tsx
  src/pages/Search/components/SearchBar/SearchBar.tsx
  src/pages/SearchListPage/components/Filters/Filters.tsx
  src/pages/SearchListPage/components/FiltersAndResult/FiltersAndResult.tsx
Labels: ⚒️ Fix, 화랑

#84 [Feat] 좋아요 API PATCH
  src/apis/Detail/patchLike.ts
  src/main.tsx
  src/pages/Detail/components/ShowInfo/ShowInfo.tsx
Labels: 다은, 🚀 API

#91 [Fix] 실시간 검색어에 일치하는 결과물 있는지 확인하는 부분 수정
  src/components/commons/SearchedShow/SearchedShow.tsx
  src/hooks/useGetSearchResult.ts
  src/pages/Search/components/SearchList/SearchList.tsx
  src/pages/SearchListPage/components/Filters/Filters.styled.ts
  src/pages/SearchListPage/components/Filters/Filters.tsx
  src/pages/SearchListPage/components/FiltersAndResult/FiltersAndResult.tsx
Labels: ⚒️ Fix, ✨ Feature, 화랑

#92 Feat/detail -> develop
  src/Router.tsx
  src/apis/Detail/fetchShowDetail.ts
  src/apis/Detail/patchLike.ts
  src/apis/Detail/postBooking.ts
  src/main.tsx
  src/pages/Detail/components/ReserveBtn/ReserveBtn.tsx
  src/pages/Detail/components/ShowInfo/ShowInfo.tsx
Labels: 다은
